travis:
  secure:
    BINSTAR_TOKEN: betiin4YAvy9kUFrTTXG+kXZCQ+0j4qj8kPLehyTBgovLsv0JelzTf7b2HC2yykObtkjJhkh6Jkn5jT8Zzus+C6UQt3zKnHYy/3sr+vZlYkjgm7NrV4nIT7hwUOeSb+XD/WfDcsC0jupZuDEOHojtTnU1hItxTC7YmrB3GGVcYuTHMHzw3cehsep2WuiMSYX8rPxcwptiaske3k2F71HL7y/HvnrFyV2GrCrYvFLdIqUYUdqoPcbJj/ZGjPL9d6aYN0neiWfWClbARWZNe4dM3XB4Dz5qdcuGWsgHTe4lm5AONSXciGYqpm1uHlAmW2fcrfGaZajnDCsIjhOqMTvtZ2FhdYkLCS3F5bY/lJnVWprAMXh5ewrvFYHKsHbA9v4YHk+o2X3NbzoZ2kcAGfB6w/5KSvtqI9UCg2QefXyFUn30JENdQ+tfbtsaP4V+Js/9i0UEw/afUPe8JVpzQpM+x7WJYiCdSyquY2NBCmfynT/DUhTyzejMy71mNIGH1R3y0jYJwIQ8sMUvoxgeXaZI+wR0V5Z6QpIzvtcrQ+uGoPB2WurvVf/o+Nf5LX/nZmqE/j5EEjHP3HS+NoWn8P3YAFGQUSj8r/vtXs8xvW9y50LBYF7HAFx1N2C+bZ2wISsK/IjYwRWQWyLqvv8SDArvLOb86j9aLY31Ogrsalaa4s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
