travis:
  secure:
    BINSTAR_TOKEN: EPGF4fTr0TESIvdbSnoaJPvDJoHkfi2guJ6yU1VRsAkYwE5cD1OecOGF67CFakEcmBetf+yLDFbfIvGX5lQZYvROQejcKVCXswXNb20I8gYCyg8PNdpCLnjKSIusYq+OEyUXHZ/HOP8qJYtvmjGOiguKA/Qx+QO06Xzt2iEQ5gvIw/+cp+/X8NyetbVgYm6xOzlf6aqT+zbBx2HMOqBZz09AJqdxUEB6DRyhKcJU5OZavoMGk67Wxq8gh0DZdri4kLTfZrTtfYuL+UNKXxy5N1RikXYV6DKm6zRuyl6Em6b6Pw9jP2gCZeM5nl2sh/hyTGRywB4zqA++tSqw/Nxs9jL+NrwPoX2SvTa9YP0kECF03f2EB3z02dlyfDnrZ5OvJXSKibe8SeCBhXZF6RXqVmCpU8Cq1k9Vaon9YH04/+JIoEoFV2DFNh31SZSgEvSlck9VdDTDX1W8pHTICYBl4nSAjgggRwQ/MTKJZhhPW1ZMa+blTbRMh2UEqTBLK9gbKH+b47UQm/LaVr8fDEx+DLJFno2C1ENvaBzICKK0HgUZvPKfMraZdHnHbN9pcaOxK6YqB4BPQjk1ctOYeh0/67tg4tLxvWUg3gpI78gd7/sPTBMUNDb0SzEhYVp0q5V5eNsny6mCRXOPg/V9aGb/EtEhSgAggEmHtzp6YB3l/yo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
